### ISSUE TITLE
Some windows have completely transparent backgrounds.

### ISSUE THREAD

**Issue by keystroke3** [NikkNakk/Brightwork-Theme#18]
There are some apps whose windows are completely transparent making it hard to see what is on it. A notable example is Winetricks. Another is all dialog and popup windows of PCManFM. The gnome-terminal is also transparent.
I have looked through the budgie css files but cannot seem to find the cause. I hope a fix comes soon.

**Comment by Staudey** [comment]
Can confirm the issue with winetricks using the latest version of Brightwork.
![Screenshot](https://i.imgur.com/9PL6Vc9.jpg)

**Comment by NikkNakk** [comment]
Think I fixed it, at least for Winetricks. 

@keystroke3 I am not having the gnome-terminal issue, mine is not transparent. Can you check your gnome-terminal preferences and get back to me?

I am going to close this issue for now, but please reopen it or resubmit it with the ones left unfixed so we can keep track of which specific applications I need to look into.

Thanks guys!

**Comment by keystroke3** [comment]
Thanks @NikkNakk  for fixing the issue for the popups, but it still persists for me in terminal. I decided to check the terminal settings, and found this:
![transparent terminal](https://user-images.githubusercontent.com/37796862/59568094-95804000-907e-11e9-9962-a40a282df7cf.gif)
The terminal background became black when I set it to use a custom theme and ignore the default.

**Comment by NikkNakk** [comment]
That is interesting, I will see if I can reproduce it on my end. This is on the most recent commit?

**Comment by keystroke3** [comment]
Yes it is. I did a git pull to update before trying and recording this. 

⁣Get BlueMail for Android ​

**Comment by NikkNakk** [comment]
No problem, I figured you did. I'll try and take a look tonight. We're still travelling around so my service is spotty. Thanks for your patience! 

Edit: This is very strange, I haven't been able to reproduce the issue. What version of Gnome Terminal is running on your system?

**Comment by keystroke3** [comment]
I am running gnome shell 3.32.2. I don't know how to check the Budgie desktop version. `uname -a` output is `Linux SiliconManjaro 4.19.49-1-MANJARO #1 SMP PREEMPT Sun Jun 9 20:24:20 UTC 2019 x86_64 GNU/Linux` I have tried this on both gnome and bugie desktops. The results are the same. I don't know what is different about our two systems. But it's ok. I use guake all the time. I don't even use gnome-terminal that much. I only use it for tasks such as htop. I will set it to have ignore system themes. And life will go on. If you are not having the problem, I doubt anyone else will.
